import pandas as pd
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from sklearn.metrics import mean_absolute_error

from src.analysis import visualizer


def train_model(model_type, X_train, y_train, X_val=None, y_val=None):
    """
    Fits the specified model type and returns the training history if available.
    """
    history = None

    if model_type == 'rf':
        if X_val is not None and y_val is not None:
            model = RandomForestRegressor(
                n_estimators=100,
                max_depth=6,
                min_samples_leaf=10,
                n_jobs=-1,
                random_state=42
            )
            history = {'train': [], 'val': []}
            max_trees = 25

            for i in range(1, max_trees + 1):
                model.n_estimators = i
                model.fit(X_train, y_train)

                # Evaluate at this specific number of trees
                train_pred = model.predict(X_train)
                val_pred = model.predict(X_val)

                history['train'].append(mean_absolute_error(y_train, train_pred))
                history['val'].append(mean_absolute_error(y_val, val_pred))
        else:
            model = RandomForestRegressor(n_estimators=100, max_depth=15, n_jobs=-1, random_state=42)
            model.fit(X_train, y_train)

    elif model_type == 'xgb':
        if X_val is not None and y_val is not None:
            model = XGBRegressor(n_estimators=300, learning_rate=0.05, max_depth=4,
                                 subsample=0.8, colsample_bytree=0.8, n_jobs=-1, random_state=42,
                                 eval_metric="mae", early_stopping_rounds=15)

            model.fit(X_train, y_train, eval_set=[(X_train, y_train), (X_val, y_val)], verbose=False)
            results = model.evals_result()
            history = {
                'train': results['validation_0']['mae'],
                'val': results['validation_1']['mae']
            }
        else:
            # Standard training fallback
            model = XGBRegressor(n_estimators=300, learning_rate=0.05, max_depth=4,
                                 subsample=0.8, colsample_bytree=0.8, n_jobs=-1, random_state=42,
                                 eval_metric="mae")
            model.fit(X_train, y_train)
    else:
        raise ValueError(f"Unknown model type: {model_type}")

    return model, history

def run_experiment(data_dict):
    """
    Runs the 8-Scenario Ablation Study for BOTH Random Forest and XGBoost dynamically.
    """
    train_df = data_dict['train_df']
    test_df = data_dict['test_df']
    all_cols = data_dict['feature_names']
    target = 'remaining_time_days'

    y_train = train_df[target]
    y_test = test_df[target]

    # 1. Control Flow: Counts (Frequency)
    f_counts = [c for c in all_cols if c.startswith('Count_')]

    # 2. Control Flow: State (Last Event + Second Last)
    f_state = [c for c in all_cols if c == 'Last_event_ID_te']
    f_last_two = [c for c in all_cols if c in ['Last_event_ID_te', 'Second_last_event_ID_te']]

    # 3. Temporal
    f_temporal = [c for c in all_cols if
                  c in ['elapsed_time_days', 'time_since_last_event', 'prefix_length', 'Month_te', 'Weekday_te']]

    # 4. Workload
    f_workload = [c for c in all_cols if 'workload' in c]

    # 5. Baseline: Case Attributes
    # Everything that was NOT generated by our pipeline is a baseline case attribute!
    pipeline_generated = set(f_counts + f_last_two + f_temporal + f_workload)
    f_attrs = [c for c in all_cols if c not in pipeline_generated]

    # Helper to ensure cols exist
    def get_cols(col_list):
        return [c for c in col_list if c in train_df.columns]

    scenarios = {
        "Case Attributes (Baseline)": get_cols(f_attrs),
        "Control Flow: Events (Freq + State)": get_cols(f_attrs + f_counts + f_state),
        "Control Flow: Frequency Only": get_cols(f_attrs + f_counts),
        "Control Flow: Last Two": get_cols(f_attrs + f_last_two),
        "Full Control Flow": get_cols(f_attrs + f_counts + f_last_two),
        "Temporal Features": get_cols(f_attrs + f_temporal),
        "Workload Features": get_cols(f_attrs + f_workload),
        "All Features": all_cols
    }

    results = []
    best_model, min_mae = None, float('inf')
    X_test_best = None

    print("\n" + "=" * 60)
    print(" RUNNING 8 SCENARIOS (RF vs XGB)")
    print("=" * 60)

    for model_name in ['rf', 'xgb']:
        print(f"\n--- Model: {model_name.upper()} ---")

        for scenario_name, features in scenarios.items():
            if not features:
                continue

            # Train
            X_train_sub = train_df[features]
            X_test_sub = test_df[features]

            model, history = train_model(model_name, X_train_sub, y_train, X_test_sub, y_test)
            y_pred = model.predict(X_test_sub)

            # Evaluate
            mae = mean_absolute_error(y_test, y_pred)
            print(f"  {scenario_name:40s} | MAE: {mae:.2f} days")

            # Plot the learning curve if history exists (XGBoost)
            if history:
                visualizer.plot_learning_curve(history, model_name.upper(), scenario_name)

            results.append({
                "Model": model_name.upper(),
                "Scenario": scenario_name,
                "MAE": mae,
                "Num_Features": len(features)
            })

            if mae < min_mae:
                min_mae = mae
                best_model = model
                X_test_best = test_df.copy()
                X_test_best['predicted_remaining'] = y_pred
                print(f"\t-> New Global Best Model!")

    print("=" * 60)
    return pd.DataFrame(results), best_model, X_test_best, y_test